FROM node:18.16.0-alpine as build

WORKDIR /app
COPY package*.json /app
# RUN npm install --only=prod
RUN npm install 
COPY . .
# RUN npm run build
CMD [ "npm","run","dev" ]

# FROM gcr.io/distroless/nodejs18-debian11 as prod
# FROM node:18.16.0-alpine as prod

# WORKDIR /app
# COPY package*.json .
# RUN npm install --only=prod
# COPY --from=build /app/dist ./dist  

# EXPOSE 3000

# CMD [ "node","./dist/src/index.js" ]

