apiVersion: skaffold/v4beta7
kind: Config
manifests:
  rawYaml:
    - "./infra/k8s-dev/**"
    - "./infra/k8s/config/**"
    - "./infra/k8s/**"
    - "./infra/db/**"
deploy:
  kubectl: {}
build:
  local:
    push: false
  artifacts:
    - image: aswines/ticketing-apigateway
      context: apigateway
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - dest: "src/**/*.ts"
            src: "."

    - image: aswines/ticketing-auth
      context: auth
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - dest: "src/**/*.ts"
            src: "."

    - image: aswines/ticketing-profile
      context: profile
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - dest: "src/**/*.ts"
            src: "."

    - image: aswines/ticketing-video
      context: video
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - dest: "src/**/*.ts"
            src: "."
