apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: app
data:
  PORT: "3001"
  NODE_ENV: "development"
  # MONGO_URL: "mongodb://localhost:27017/auth"
  BASE_URL: "http://localhost:3000/api/v1/auth/user"
  JWT_SECRET: "sz4kUoKTEpemjr6E29kMzCmC3BzAQ6Yfi2UyWjHKSGhAPdGgH2WfcoTZUBWD3uF"
  MAIL_URL: "http://localhost:4200/email-verification"
  KAFKA_BROKER: "my-kafka.kafka.svc.cluster.local:9092"
