apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-depl
  namespace: app
spec:
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
        - name: profile
          image: aswines/ticketing-profile
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: profile-config
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb-atlas-profile
                  key: MONGO_URL
          # resources:
          #   requests:
          #     memory: "1Gi"
          #     cpu: "500m"
          #   limits:
          #     memory: "2Gi"
          #     cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: profile-srv
  namespace: app
spec:
  selector:
    app: profile
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
