apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-resources
  namespace: app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: upload
  name: my-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-role-binding
  namespace: upload
subjects:
  - kind: ServiceAccount
    name: create-resources
    namespace: app
roleRef:
  kind: Role
  name: my-role
  apiGroup: rbac.authorization.k8s.io
