apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-depl
  namespace: app
spec:
  selector:
    matchLabels:
      app: video
  template:
    metadata:
      labels:
        app: video
    spec:
      serviceAccountName: create-resources
      containers:
        - name: video
          image: aswines/ticketing-video
          ports:
            - containerPort: 3003
          envFrom:
            - configMapRef:
                name: video-config
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-s3
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-s3
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: aws-s3
                  key: AWS_BUCKET
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-s3
                  key: AWS_REGION
          # resources:
          #   requests:
          #     memory: "1Gi"
          #     cpu: "500m"
          #   limits:
          #     memory: "2Gi"
          #     cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: video-srv
  namespace: app
spec:
  selector:
    app: video
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
